language: scala

scala:
  - 2.12.8

script:
  - scripts/travis.sh

cache:
  directories:
  - $HOME/.sbt/1.0/zinc
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/preloaded
  - $HOME/.ivy2/cache

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
